'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class svmu_calon_manual1

    '''<summary>
    '''txtRujukan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRujukan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMsgRujukan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgRujukan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMYKAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMYKAD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMsgMYKAD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgMYKAD As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAngkaGiliran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAngkaGiliran As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMsgAngkaGiliran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsgAngkaGiliran As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSemak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSemak As Global.System.Web.UI.WebControls.Button
End Class
