'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class admin_penetapan_pemeriksa

    '''<summary>
    '''penetapan_pemeriksa_bmsetara1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents penetapan_pemeriksa_bmsetara1 As Global.apkv_v2_admin.penetapan_pemeriksa_bmsetara
End Class
