'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class jana_keseluruhan_vokasional
    
    '''<summary>
    '''jana_keseluruhan_vokasional1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents jana_keseluruhan_vokasional1 As Global.apkv_v2_admin.jana_keseluruhan_vokasional1
End Class
