'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class panel_jana_borang_k15_sejarah
    
    '''<summary>
    '''panel_jana_borang_k15_sejarah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel_jana_borang_k15_sejarah As Global.apkv_v2_admin.panel_jana_borang_k15_sejarah1
End Class
