'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pembetulan_markah_PBA
    
    '''<summary>
    '''pembetulan_markah_PB_akademik control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pembetulan_markah_PB_akademik As Global.apkv_v2_admin.pembetulan_markah_PB_akademik
End Class
