'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pembetulan_markah_PBV
    
    '''<summary>
    '''pembetulan_markah_PB_vokasional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pembetulan_markah_PB_vokasional As Global.apkv_v2_admin.pembetulan_markah_PB_vokasional
End Class
