'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pendaftaran_calon_ulang_online

    '''<summary>
    '''pendaftaran_calon_ulang_online control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pendaftaran_calon_ulang_online As Global.apkv_v2_admin.pendaftaran_calon_ulang_online1
End Class
