'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pentaksirbm_senarai_kjpp_bm41

    '''<summary>
    '''pentaksirbm_senarai_kjpp_bm4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pentaksirbm_senarai_kjpp_bm4 As Global.apkv_v2_admin.pentaksirbm_senarai_kjpp_bm4
End Class
