'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pentaksirbm_admin_senarai_markah1

    '''<summary>
    '''pentaksirbm_admin_senarai_markah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pentaksirbm_admin_senarai_markah As Global.apkv_v2_admin.pentaksirbm_admin_senarai_markah
End Class
