'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class pentaksirbm_calon_bm3_serah

    '''<summary>
    '''pentaksirbm_calon_bm3_serah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pentaksirbm_calon_bm3_serah As Global.apkv_v2_admin.pentaksirbm_calon_bm3_serah1
End Class
