'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class senarai_muatnaik_bahan
    
    '''<summary>
    '''senarai_muatnaik_bahan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents senarai_muatnaik_bahan1 As Global.apkv_v2_admin.senarai_muatnaik_bahan1
End Class
