'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class svmu_pembayaran_pendaftaran2

    '''<summary>
    '''svmu_pembayaran_pendaftaran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents svmu_pembayaran_pendaftaran As Global.apkv_v2_admin.svmu_pembayaran_pendaftaran
End Class
