'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class svmu_slip_keputusan_ulangan1

    '''<summary>
    '''svmu_slip_keputusan_ulangan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents svmu_slip_keputusan_ulangan As Global.apkv_v2_admin.svmu_slip_keputusan_ulangan
End Class
